# Generated by Django 3.0.5 on 2022-07-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_scoremodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoremodel',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
