# Generated by Django 3.0.5 on 2022-07-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_scoremodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoremodel',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
