# Generated by Django 3.0.5 on 2022-07-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_auto_20220717_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoremodel',
            name='time',
        ),
    ]
