# Generated by Django 3.0.5 on 2022-07-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_remove_scoremodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoremodel',
            name='isTestGiven',
            field=models.BooleanField(default=False),
        ),
    ]
